### ISSUE TITLE
Implementing log transport

### ISSUE THREAD

**Issue by cia-rana** [cybozu-go/kkok#3]
**log transport** logs alerts.

## Description
I think that we needs **log transport** berause it it very useful for us to implement new kkok features, debug, etc.

### construction parameters
|Name|Type|Default|Description|
|:-|:-|:-|:-|
|label|string|""|Arbitrary string label.|
|all|bool|false|If true, the output format will be a list of `kkok.Alert`s objects in JSON. Otherwise, the output format will be multiple `kkok.Alert`s object in JSON.|

### TOML configuration example
```toml
[[route.notify]]
type = "log"
label = "log alerts"
all = true
```
